<?php

//See also soluntion 4, which uses the same idea but achieves it proceedurally
//the solution below is a single php expression which uses functional ideas
function getRating() {
	//take resulting array and replace string elements with img tags & join it into a string
	return implode("\n", array_map(function($s) { return sprintf('<img src="assets/%s.png"/>', $s); },
		//array_map: apply a function(#1) that translates numbers(#3) to strings over an array (#2)
		 array_map(
				//function that translates a number 0 - 6 to a string (star_empty, star_partial, star_full)
				function ($v) { 
					//create an array where 0 = empty, 1 = partial and 2 - 6 = full
					return array_merge(['star_partial', 'star_empty'], 
                                                           ['star_full', 'star_full', 'star_full'])[$v]; //dereference (get value out of array) at the $v th place
				},
				
				//#2 generate array of numbers reverse sorted so 6 (full) is first and 0 (empty) is last
				//call the a sorting function (#A) on an array (#B)
				call_user_func(
					//#A sorting function, used because php's rsort does not return its result
					function($arr) { 
						rsort($arr); return $arr; 
					}, 
					//#B array generated by replacing each slot of an empty array with a random number 0 - 6
					array_map(function($v) { 
							return rand($v,4); //#3 Numbers generated here
						}, 
						
						//empty array that is mapped over by the function above
						[1,1,1,1,0]
					)
				)
			)
	));
}

echo getRating();